// "use client";
// import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from './header';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex justify-center items-start">
					<div className="absolute top-0">
						<Header />
					</div>
				</div>

				{children}
			</body>
		</html>
	);
}
