// "use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./header";
import { GlobalContextProvider } from "./context/context";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<GlobalContextProvider>
				<body className={inter.className}>
					<div className="flex justify-center">
						<div className="fixed top-0 z-50">
							<Header />
						</div>
					</div>

					{children}
				</body>
			</GlobalContextProvider>
		</html>
	);
}
